use local file, if they exist, instead of pulling from affy.com

diff --git a/linode_build_v00/stackscript b/linode_build_v00/stackscript
--- a/linode_build_v00/stackscript
+++ b/linode_build_v00/stackscript
@@ -1,5 +1,41 @@
 #!/bin/bash
 
+if [[ $EUID -ne 0 ]]; then
+   echo "You must be root to run this script. Aborting...";
+   exit 1;
+fi
+
+##########
+# Make sure we have all of the files locally
+
+if [ ! -f sysctl.conf ];
+then
+  echo "Getting Sysctl"
+  wget -q http://www.affy.com/linode_build/sysctl.conf
+fi
+if [ ! -f hadoop-0.20.2.tar.gz ];
+then
+  echo "Getting Hadoop"
+  wget -q http://www.affy.com/linode_build/hadoop-0.20.2.tar.gz
+  wget -q http://www.affy.com/linode_build/core-site.xml 
+  wget -q http://www.affy.com/linode_build/hdfs-site.xml
+  wget -q http://www.affy.com/linode_build/mapred-site.xml
+  wget -q http://www.affy.com/linode_build/hadoop-env.sh
+fi
+if [ ! -f zookeeper-3.4.3.tar.gz ];
+then
+  echo "Getting Zookeeper"
+  wget -q http://www.affy.com/linode_build/zookeeper-3.4.3.tar.gz
+  wget -q http://www.affy.com/linode_build/zoo.cfg
+fi
+if [ ! -f accumulo-site.xml ];
+then
+  echo "Getting Accumulo Configuration"
+  wget -q http://www.affy.com/linode_build/accumulo-site.xml
+fi
+
+CDIR=`pwd`
+
 PASSWORD=`openssl passwd -1 password`
 
 LOGFILE=/tmp/startup.log
@@ -26,8 +62,9 @@ function add_a_user {
 # using SSH for the first time.
 ssh-keyscan -t rsa,dsa localhost >> /etc/ssh/ssh_known_hosts
 
+##########
 # Update the sysctl file to set swappiness. And set it for the current session.
-wget -q http://www.affy.com/linode_build/sysctl.conf -O /etc/sysctl.conf
+cp $CDIR/sysctl.conf /etc/sysctl.conf
 sysctl vm.swappiness=10
 
 add_a_user accumulo
@@ -43,24 +80,23 @@ echo "export PATH=\$ACCUMULO_HOME/bin:\$HADOOP_HOME/bin:\$JAVA_HOME/bin:\$ZOOKEE
 
 echo "Created /etc/rc.local" >> $LOGFILE
 
-apt-get -y install curl git maven2 openssh-server openssh-client openjdk-6-jdk subversion screen fail2bin
+apt-get -y install curl git maven2 openssh-server openssh-client openjdk-6-jdk subversion screen
+#apt-get -y fail2bin
 echo "Installed packages" >> $LOGFILE
 
 # Disable IP6
-sudo echo "#disable ipv6" >> /etc/sysctl.conf
-sudo echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
-sudo echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
-sudo echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
+echo "#disable ipv6" >> /etc/sysctl.conf
+echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
+echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
+echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
 
 # install and configure hadoop
 cd /usr/local
-wget -q http://www.affy.com/linode_build/hadoop-0.20.2.tar.gz
-tar xvfz hadoop-0.20.2.tar.gz
-rm hadoop-0.20.2.tar.gz
-wget -q http://www.affy.com/linode_build/core-site.xml -O /usr/local/hadoop-0.20.2/conf/core-site.xml
-wget -q http://www.affy.com/linode_build/hdfs-site.xml -O /usr/local/hadoop-0.20.2/conf/hdfs-site.xml
-wget -q http://www.affy.com/linode_build/mapred-site.xml -O /usr/local/hadoop-0.20.2/conf/mapred-site.xml
-wget -q http://www.affy.com/linode_build/hadoop-env.sh -O /usr/local/hadoop-0.20.2/conf/hadoop-env.sh
+tar xvfz $CDIR/hadoop-0.20.2.tar.gz
+cp $CDIR/core-site.xml /usr/local/hadoop-0.20.2/conf/core-site.xml
+cp $CDIR/hdfs-site.xml /usr/local/hadoop-0.20.2/conf/hdfs-site.xml
+cp $CDIR/mapred-site.xml /usr/local/hadoop-0.20.2/conf/mapred-site.xml
+cp $CDIR/hadoop-env.sh /usr/local/hadoop-0.20.2/conf/hadoop-env.sh
 chown -R hadoop:hadoop /usr/local/hadoop-0.20.2
 ln -s hadoop-0.20.2 hadoop
 
@@ -77,10 +113,8 @@ su hadoop -c "/usr/local/hadoop/bin/start-mapred.sh"
 
 # install and configure zookeeper
 cd /usr/local
-wget -q http://www.affy.com/linode_build/zookeeper-3.4.3.tar.gz
-tar xvfz zookeeper-3.4.3.tar.gz
-rm zookeeper-3.4.3.tar.gz
-wget -q http://www.affy.com/linode_build/zoo.cfg -O /usr/local/zookeeper-3.4.3/conf/zoo.cfg
+tar xvfz $CDIR/zookeeper-3.4.3.tar.gz
+cp $CDIR/zoo.cfg /usr/local/zookeeper-3.4.3/conf/zoo.cfg
 chown -R zookeeper:zookeeper /usr/local/zookeeper-3.4.3
 ln -s /usr/local/zookeeper-3.4.3 /usr/local/zookeeper
 mkdir /zookeeper_tmp_dir
@@ -108,7 +142,7 @@ mkdir /usr/local/accumulo-1.5.0-SNAPSHOT/logs
 mkdir /usr/local/accumulo-1.5.0-SNAPSHOT/walogs
 chmod g+w /usr/local/accumulo-1.5.0-SNAPSHOT/lib/ext
 cp /usr/local/accumulo-1.5.0-SNAPSHOT/conf/examples/512MB/standalone/* /usr/local/accumulo-1.5.0-SNAPSHOT/conf
-wget -q http://www.affy.com/linode_build/accumulo-site.xml -O /usr/local/accumulo-1.5.0-SNAPSHOT/conf/accumulo-site.xml
+cp $CDIR/accumulo-site.xml /usr/local/accumulo-1.5.0-SNAPSHOT/conf/accumulo-site.xml
 chown -R accumulo:accumulo /usr/local/accumulo-1.5.0-SNAPSHOT
 ln -s /usr/local/accumulo-1.5.0-SNAPSHOT accumulo
 
